name: Java CI with Maven and Dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout main branch
      - name: checkout main branch from Github
        uses: actions/checkout@v3

      # Setup JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      # Build and Test Maven project
      - name: Build with Maven
        run: |
          mvn clean install
          mvn test
          
      # Use secrets to login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Setup BuildX
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Build and push image
      - name: Build and push Docker image to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calc:latest
          
      # Install docker-compose
      - name: Install Docker compose
        run: sudo apt install docker-compose
          
      # Run the project remotely with Ansible
      - name: Execute project on Ansible
        uses: tomasnorre/ansible-cli-client@0.0.2
        with:
          command: "ansible-playbook calc-playbook.yml -i inventory -vvv"

          
